In [47]:
import numpy as np, pandas as pd, scipy as sp, random

In [3]:
data = [[1,4],[2,5],[3,6],[10,20]]

In [4]:
# creating a dataframe from a dictionary 
states = ['California','Alabama','Florida','New York','Texas']
population = [38332500, 4888722, 21477737, 19651127, 29000000]

dict_states = {'State':states,'Population':population}
df_population = pd.DataFrame(dict_states)
df_population

State  Population
0  California    38332500
1     Alabama     4888722
2     Florida    21477737
3    New York    19651127
4       Texas    29000000

In [5]:
# dataframe from a csv file 

df_bmi = pd.read_csv(r"C:\Users\user\Downloads\weight-height.csv")

In [6]:
df_bmi.tail(10)

Gender     Height      Weight
9990  Female  63.179498  141.266100
9991  Female  62.636675  102.853563
9992  Female  62.077832  138.691680
9993  Female  60.030434   97.687432
9994  Female  59.098250  110.529686
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

In [7]:
df_bmi.head(10)

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801
5   Male  67.253016  152.212156
6   Male  68.785081  183.927889
7   Male  68.348516  167.971111
8   Male  67.018950  175.929440
9   Male  63.456494  156.399676

In [8]:
df_bmi.shape

(10000, 3)

In [9]:
pd.set_option('display.max_rows', 1000)
df_bmi


Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [10]:
print(df_bmi.columns)

Index(['Gender', 'Height', 'Weight'], dtype='object')


In [11]:
df_bmi

Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [12]:
df_bmi.shape

(10000, 3)

In [13]:
df_bmi.index

RangeIndex(start=0, stop=10000, step=1)

In [14]:
df_bmi.columns

Index(['Gender', 'Height', 'Weight'], dtype='object')

In [15]:
df_bmi.dtypes

Gender     object
Height    float64
Weight    float64
dtype: object

#Methods 

In [16]:
df_bmi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  10000 non-null  object 
 1   Height  10000 non-null  float64
 2   Weight  10000 non-null  float64
dtypes: float64(2), object(1)
memory usage: 234.5+ KB


In [17]:
df_bmi.describe()

Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989698

In [18]:
len(df_bmi)

10000

In [19]:
max(df_bmi.index)

9999

In [20]:
min(df_bmi.index)

0

In [21]:
print(type(df_bmi))

<class 'pandas.core.frame.DataFrame'>


In [22]:
round(df_bmi, 2)

Gender  Height  Weight
0       Male   73.85  241.89
1       Male   68.78  162.31
2       Male   74.11  212.74
3       Male   71.73  220.04
4       Male   69.88  206.35
...      ...     ...     ...
9995  Female   66.17  136.78
9996  Female   67.07  170.87
9997  Female   63.87  128.48
9998  Female   69.03  163.85
9999  Female   61.94  113.65

[10000 rows x 3 columns]

In [23]:
df_bmi.columns

Index(['Gender', 'Height', 'Weight'], dtype='object')

In [24]:
df_bmi['Gender']

0         Male
1         Male
2         Male
3         Male
4         Male
         ...  
9995    Female
9996    Female
9997    Female
9998    Female
9999    Female
Name: Gender, Length: 10000, dtype: object

In [25]:
# check out the data type of a column 
type(df_bmi['Gender'])

pandas.core.series.Series

In [26]:
df_bmi['Gender'].index
df_bmi['Gender'].head()

0    Male
1    Male
2    Male
3    Male
4    Male
Name: Gender, dtype: object

In [27]:
#selecting one column
df_bmi.Gender

0         Male
1         Male
2         Male
3         Male
4         Male
         ...  
9995    Female
9996    Female
9997    Female
9998    Female
9999    Female
Name: Gender, Length: 10000, dtype: object

In [28]:
# checking the columns

df_bmi.columns

Index(['Gender', 'Height', 'Weight'], dtype='object')

In [29]:
#select multiple columns using square brackets
df_bmi[['Gender', 'Height']]

Gender     Height
0       Male  73.847017
1       Male  68.781904
2       Male  74.110105
3       Male  71.730978
4       Male  69.881796
...      ...        ...
9995  Female  66.172652
9996  Female  67.067155
9997  Female  63.867992
9998  Female  69.034243
9999  Female  61.944246

[10000 rows x 2 columns]

In [30]:
df_bmi.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

# adding a new column


In [31]:
# adding a new column to the dataframe 
df_bmi['Age'] = 70 

In [32]:
df_bmi

Gender     Height      Weight  Age
0       Male  73.847017  241.893563   70
1       Male  68.781904  162.310473   70
2       Male  74.110105  212.740856   70
3       Male  71.730978  220.042470   70
4       Male  69.881796  206.349801   70
...      ...        ...         ...  ...
9995  Female  66.172652  136.777454   70
9996  Female  67.067155  170.867906   70
9997  Female  63.867992  128.475319   70
9998  Female  69.034243  163.852461   70
9999  Female  61.944246  113.649103   70

[10000 rows x 4 columns]

# adding a new column with an array 

In [33]:
# create an array of 1000 elements 
np.arange(0,1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [34]:
np.random.uniform(1,100, size=100)

array([ 4.84146583, 86.09504079, 64.52347045,  5.02350403,  6.79698897,
       75.51898055, 84.41336024, 73.28013258, 86.8826279 , 17.49842684,
       13.40783599, 41.08453289, 80.29073709,  6.24912825, 90.582134  ,
       29.38948668, 98.6142163 , 58.35568352, 80.51375675, 70.94993367,
       96.60453624,  1.94273235, 64.89118698, 46.92301947, 13.1029758 ,
       44.69590686, 16.50400207, 67.95715134, 45.07509745, 89.31133352,
       82.01300465, 87.3588856 , 38.57972806, 79.2115294 ,  5.14137689,
       73.02355845, 37.09920831, 17.99432928, 63.40790833,  3.74956088,
       77.01421854, 76.09674869, 33.00445236, 48.38289818, 91.55363418,
       77.99364597, 78.61471573,  5.71782942, 75.07058852, 83.10883127,
       18.92956921,  3.67775455, 75.90691745, 78.49087261,  2.07852858,
       84.98179877, 24.30690371,  1.5112981 , 22.31425783, 87.97378991,
       25.70251342, 63.72637902,  4.28939274, 67.7908619 , 34.24540126,
       12.43569388, 55.55284804, 54.15538416, 54.75727797, 28.59

In [35]:
# create random numbers for the  new score columns 
score1 = np.random.randint(0, 100, 1000)
score2 = np.random.randint(0, 100, 1000)

In [36]:
score1

array([87, 80, 97, 16, 79, 97, 83, 42, 37, 21, 17, 60, 68, 72, 15, 37, 74,
       39,  2,  8, 55, 72, 29, 56, 12, 81, 96, 59,  9, 87, 26,  7, 56,  4,
        6, 15,  8, 68, 91, 56, 71, 44,  2,  0, 63, 26, 10, 94, 47, 59, 12,
       79, 68, 50, 43, 90, 48, 38, 72, 45, 28, 64, 80, 35,  6, 90, 36, 35,
       85, 11, 63, 35, 24, 54, 64, 55, 19, 50, 69, 62, 30, 30, 53,  1, 17,
       34, 89, 44, 97, 95, 19, 32, 56, 99, 51,  5, 90, 69, 14,  9, 27,  0,
       43, 62, 99, 53, 51, 49, 84, 41, 31, 86, 34, 63, 35,  1,  1, 73, 48,
       76, 61, 84, 89, 93, 46,  6, 78,  9, 27, 44, 71, 61, 74,  5, 26, 60,
       30, 41,  9, 94, 37, 93, 95, 52, 82, 91, 53, 65, 54, 73, 45,  8, 57,
       78, 10, 88, 17, 99, 71, 57, 86, 18, 42, 78, 77, 97,  7,  0, 28,  0,
       31, 14, 20, 31, 71, 74,  9, 71,  1, 13, 88, 39, 10, 61, 10, 60,  3,
       74, 30, 36, 93, 21,  5, 16, 13, 61, 27, 51, 81, 16, 10, 86,  0, 97,
       59, 20, 92, 93, 73, 71, 18, 36, 26, 25, 49, 35, 40, 37, 77, 96,  0,
       97, 66, 84, 29, 58

In [37]:
df_bmi

Gender     Height      Weight  Age
0       Male  73.847017  241.893563   70
1       Male  68.781904  162.310473   70
2       Male  74.110105  212.740856   70
3       Male  71.730978  220.042470   70
4       Male  69.881796  206.349801   70
...      ...        ...         ...  ...
9995  Female  66.172652  136.777454   70
9996  Female  67.067155  170.867906   70
9997  Female  63.867992  128.475319   70
9998  Female  69.034243  163.852461   70
9999  Female  61.944246  113.649103   70

[10000 rows x 4 columns]

In [38]:
df_bmi['Age'].sum()

700000

In [39]:
df_bmi['Age'].count()

10000

In [43]:
int_lang_score = np.random.randint(1,100,1000)

In [44]:
min(int_lang_score)
max(int_lang_score)

99

In [46]:
# create random float number \
np.random.uniform(1,100,100)

array([67.45465073, 92.9410079 ,  8.776929  , 79.63939177, 39.38130947,
       77.65270093, 27.34025036, 92.9537767 ,  9.48630852, 71.64965235,
        6.7521439 , 26.32466636, 21.45699283, 42.47735324, 96.39142222,
       46.73082049, 98.60840072, 93.56021266, 82.10818625, 11.63655109,
        1.9876149 , 84.17690149, 63.2138216 , 49.67680364, 76.74740612,
       94.27269639, 93.44656863, 15.45700922, 74.44455015, 54.28423858,
       45.01869234, 19.12355121, 88.46885576, 56.92319723, 22.63384206,
       19.57533171, 19.02098634, 91.69302392, 59.1020309 , 75.98180113,
       42.06482562, 20.57062459, 47.90244591, 59.99071401, 83.67663404,
       16.87174754, 90.64810732, 22.24295631, 40.88329219, 99.57880324,
       58.27815344, 39.80917628, 61.06910539, 34.70414553, 21.10891015,
       30.36898033,  4.61023653, 65.02094991, 75.0072665 , 12.32097161,
       70.27708012, 98.62506117, 38.29383053, 20.03694706, 81.35734031,
       95.29340958, 51.11845941, 88.00085265,  9.50344313, 48.71

In [49]:
# creating non repetitive values for the index 
new_index =np.arange(0,1000)

In [55]:
# shuffling the indexes 
random.shuffle(new_index)
new_index

array([174, 825, 233, 774,  77, 510, 932, 663, 946, 121, 832, 943, 204,
       229,  27, 822, 864, 518, 493, 381, 122, 243, 850, 937, 983, 182,
        71, 884, 603, 785, 349, 959, 100,  73, 880, 712, 625, 564,  91,
       385, 878,  98, 255, 380, 802, 681, 618, 478, 156, 662, 687, 436,
       355, 107, 172, 475, 749, 347, 273, 700,  31,  69, 168, 101, 350,
       810, 487, 666, 378, 907, 209, 362, 836, 483, 292, 207, 300, 930,
       630, 985, 950, 918, 592, 159, 966, 570, 960, 348, 973,  47, 261,
       678,  16, 458, 165, 143, 833, 544, 892, 173,   2, 853, 926, 587,
       580, 353, 286, 569, 791, 844, 531, 757, 642,  67, 639, 951, 244,
       653, 726, 117, 486,  84, 870, 713, 306, 779,  54, 432, 619, 452,
       866, 981, 230, 835, 982, 496, 139,   1, 957, 274, 106, 858,  26,
       685, 923, 997, 473, 307, 585, 281,  50,  89, 599, 402, 418, 264,
       538, 572, 319, 368, 901, 133, 940, 448, 484,  75, 329, 814,  87,
       342, 978, 311, 272,  43, 608, 931, 508, 500, 359, 958, 82

In [ ]:
# create a new column with new index

